using System;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Lab11
{
    public class MovieList
    {
        private ArrayList _movieList = new ArrayList
            {
                new Movie("51 Degrees North",2015,"scifi"),
                new Movie("2001: A Space Odyssey",1968,"scifi"),
                new Movie("Aliens",1986,"scifi"),
                new Movie("Android",1982,"scifi"),
                new Movie("Arena",1989,"scifi"),
                new Movie("The Noah's Ark Principle",1984,"scifi"),
                new Movie("Armageddon",1998,"scifi"),
                new Movie("Assignment: Outer Space",1960,"scifi"),
                new Movie("A Beautiful Planet",2016,"scifi"),
                new Movie("Cargo",2009,"scifi"),
                new Movie("The Cloverfield Paradox",2018,"scifi"),
                new Movie("Conquest of Space",1955,"scifi"),
                new Movie("Contact",1997,"scifi"),
                new Movie("Dante 01",2008,"scifi"),
                new Movie("Dark City",1998,"scifi"),
                new Movie("The Day After Tomorrow",2004,"scifi"),
                new Movie("Earth II",1971,"scifi"),
                new Movie("Elysium",2013,"scifi"),
                new Movie("Ender's Game",2013,"scifi"),
                new Movie("Enemy Mine",1985,"scifi"),
                new Movie("Event Horizon",1997,"scifi"),
                new Movie("Fortress 2: Re-Entry",2000,"scifi"),
                new Movie("Geostorm",2017,"scifi"),
                new Movie("Gravity",2013,"scifi"),
                new Movie("The Green Slime",1968,"scifi"),
                new Movie("Hellraiser: Bloodline",1996,"scifi"),
                new Movie("Interstellar",2014,"scifi"),
                new Movie("Jason X",2002,"scifi"),
                new Movie("Life",2017,"scifi"),
                new Movie("Lockout",2012,"scifi"),
                new Movie("Love",2011,"scifi"),
                new Movie("Marooned",1969,"scifi"),
                new Movie("Mission to Mars",2000,"scifi"),
                new Movie("Mission to Mir",1997,"scifi"),
                new Movie("Moonraker",1979,"scifi"),
                new Movie("Mutiny in Outer Space",1965,"scifi"),
                new Movie("Mystery Science Theater 3000: The Movie",1996,"scifi"),
                new Movie("Oblivion",2013,"scifi"),
                new Movie("Planet of the Apes",2001,"scifi"),
                new Movie("Project Moonbase",1953,"scifi"),
                new Movie("Queen of Outer Space",1958,"scifi"),
                new Movie("Robotech: The Shadow Chronicles",2006,"scifi"),
                new Movie("Rogue One: A Star Wars Story",2016,"scifi"),
                new Movie("Salyut-7",2017,"scifi"),
                new Movie("Solaris",1972,"scifi"),
                new Movie("Solaris",2002,"scifi"),
                new Movie("SpaceCamp",1986,"scifi"),
                new Movie("Space Station 3D",2002,"scifi"),
                new Movie("Space Station 76",2014,"scifi"),
                new Movie("Star Crystal",1986,"scifi"),
                new Movie("Star Trek Beyond",2016,"scifi"),
                new Movie("Star Trek: The Motion Picture",1979,"scifi"),
                new Movie("Star Trek II: The Wrath of Khan",1982,"scifi"),
                new Movie("Star Trek III: The Search for Spock",1984,"scifi"),
                new Movie("Star Trek IV: The Voyage Home",1986,"scifi"),
                new Movie("Star Trek V: The Final Frontier",1989,"scifi"),
                new Movie("Star Trek VI: The Undiscovered Country",1991,"scifi"),
                new Movie("Star Wars: Episode III - Revenge of the Sith",2005,"scifi"),
                new Movie("Star Wars: Episode IV - A New Hope",1977,"scifi"),
                new Movie("Star Wars: Episode VI - Return of the Jedi",1983,"scifi"),
                new Movie("Starship Troopers",1997,"scifi"),
                new Movie("Starship Troopers: Invasion",2012,"scifi"),
                new Movie("Titan A.E.",2000,"scifi"),
                new Movie("Valerian and the City of a Thousand Planets",2017,"scifi"),
                new Movie("Virus",1999,"scifi"),
                new Movie("War of the Planets",1966,"scifi"),
                new Movie("Zenon: Girl of the 21st Century",1999,"scifi"),
                new Movie("Zenon: The Zequel",2001,"scifi"),
                new Movie("Zenon: Z3",2004,"scifi"),
                new Movie("King Kong (1933 film)|King Kong",1933,"horror"),
                new Movie("Wasei Kingu Kongu",1933,"horror"),
                new Movie("King Kong Appears in Edo",1938,"horror"),
                new Movie("The Beast From 20,000 Fathoms",1953,"horror"),
                new Movie("Godzilla (1954 film)|Godzilla",1954,"horror"),
                new Movie("Godzilla Raids Again",1955,"horror"),
                new Movie("King Kong vs. Godzilla",1962,"horror"),
                new Movie("Mothra vs. Godzilla",1964,"horror"),
                new Movie("Ghidorah, the Three-Headed Monster",1964,"horror"),
                new Movie("Invasion of Astro-Monster",1965,"horror"),
                new Movie("Ebirah, Horror of the Deep",1966,"horror"),
                new Movie("Son of Godzilla",1967,"horror"),
                new Movie("Destroy All Monsters",1968,"horror"),
                new Movie("All Monsters Attack",1969,"horror"),
                new Movie("Godzilla vs. Hedorah",1971,"horror"),
                new Movie("Godzilla vs. Gigan",1972,"horror"),
                new Movie("Godzilla vs. Megalon",1973,"horror"),
                new Movie("Godzilla vs. Mechagodzilla",1974,"horror"),
                new Movie("Terror of Mechagodzilla",1975,"horror"),
                new Movie("The Return of Godzilla",1984,"horror"),
                new Movie("Godzilla vs. Biollante",1989,"horror"),
                new Movie("Godzilla vs. King Ghidorah",1991,"horror"),
                new Movie("Godzilla vs. Mothra",1992,"horror"),
                new Movie("Godzilla vs. Mechagodzilla II",1993,"horror"),
                new Movie("Godzilla vs. SpaceGodzilla",1994,"horror"),
                new Movie("Godzilla vs. Destoroyah",1995,"horror"),
                new Movie("Godzilla 2000",1999,"horror"),
                new Movie("Godzilla vs. Megaguirus",2000,"horror"),
                new Movie("Godzilla, Mothra and King Ghidorah: Giant Monsters All-Out Attack",2001,"horror"),
                new Movie("Godzilla Against Mechagodzilla",2002,"horror"),
                new Movie("Godzilla: Tokyo S.O.S.",2003,"horror"),
                new Movie("Godzilla: Final Wars",2004,"horror"),
                new Movie("Shin Godzilla",2016,"horror"),
                new Movie("Godzilla: Planet of the Monsters",2017,"horror"),
                new Movie("Godzilla: City on the Edge of Battle",2018,"horror"),
                new Movie("It Came from Beneath the Sea",1955,"horror"),
                new Movie("Rodan (film)|Rodan",1956,"horror"),
                new Movie("The Giant Claw",1957,"horror"),
                new Movie("The Mysterians",1957,"horror"),
                new Movie("20 Million Miles to Earth",1957,"horror"),
                new Movie("Varan the Unbelievable",1958,"horror"),
                new Movie("The Giant Behemoth",1959,"horror"),
                new Movie("The Giant Gila Monster",1959,"horror"),
                new Movie("The Three Treasures",1959,"horror"),
                new Movie("Reptilicus",1961,"horror"),
                new Movie("Mothra (film)|Mothra",1961,"horror"),
                new Movie("Gorgo (film)|Gorgo",1961,"horror"),
                new Movie("Gorath",1962,"horror"),
                new Movie("Atragon",1963,"horror"),
                new Movie("Dogora",1964,"horror"),
                new Movie("Frankenstein Conquers the World",1965,"horror"),
                new Movie("Gamera: The Giant Monster",1965,"horror"),
                new Movie("Gamera vs. Barugon",1966,"horror"),
                new Movie("Gamera vs. Gyaos",1967,"horror"),
                new Movie("Gamera vs. Viras",1968,"horror"),
                new Movie("Gamera vs. Guiron",1969,"horror"),
                new Movie("Gamera vs. Jiger",1970,"horror"),
                new Movie("Gamera vs. Zigra",1971,"horror"),
                new Movie("Gamera: Super Monster",1980,"horror"),
                new Movie("The Magic Serpent",1966,"horror"),
                new Movie("Daimajin (1966 film)|Daimajin",1966,"horror"),
                new Movie("The War of the Gargantuas",1966,"horror"),
                new Movie("The X from Outer Space",1967,"horror"),
                new Movie("Monster X Strikes Back: Attack the G8 Summit",2008,"horror"),
                new Movie("Gappa: The Triphibian Monster",1967,"horror"),
                new Movie("King Kong Escapes",1967,"horror"),
                new Movie("Ultraman (1967 film)|Ultraman",1967,"horror"),
                new Movie("Ultraman, Ultraseven: Great Violent Monster Fight",1969,"horror"),
                new Movie("The 6 Ultra Brothers vs. the Monster Army",1974,"horror"),
                new Movie("Ultraman (1979 film)|Ultraman",1979,"horror"),
                new Movie("Ultraman: Great Monster Decisive Battle",1979,"horror"),
                new Movie("Ultraman Zoffy: Ultra Warriors vs. the Giant Monster Army",1984,"horror"),
                new Movie("Ultraman Story",1984,"horror"),
                new Movie("Ultraman: The Adventure Begins",1987,"horror"),
                new Movie("Ultra Q The Movie: Legend of the Stars",1990,"horror"),
                new Movie("Ultraman Zearth",1996,"horror"),
                new Movie("Ultraman Tiga & Ultraman Dyna: Warriors of the Star of Light",1998,"horror"),
                new Movie("Ultraman Gaia: The Battle in Hyperspace",1999,"horror"),
                new Movie("Ultraman Tiga: The Final Odyssey",2000,"horror"),
                new Movie("Ultraman Cosmos: The First Contact",2001,"horror"),
                new Movie("Ultraman Cosmos 2: The Blue Planet",2002,"horror"),
                new Movie("Ultraman Cosmos vs. Ultraman Justice: The Final Battle",2003,"horror"),
                new Movie("Ultraman Mebius & Ultraman Brothers",2006,"horror"),
                new Movie("Superior Ultraman 8 Brothers",2008,"horror"),
                new Movie("Mega Monster Battle: Ultra Galaxy|Mega Monster Battle: Ultra Galaxy Legends",2009,"horror"),
                new Movie("Ultraman Zero: The Revenge of Belial",2010,"horror"),
                new Movie("Ultraman Saga",2012,"horror"),
                new Movie("Ultraman Ginga Theater Special",2013,"horror"),
                new Movie("Ultraman Ginga Theater Special: Ultra Monster Hero Battle Royal!",2014,"horror"),
                new Movie("Ultraman Ginga S The Movie",2015,"horror"),
                new Movie("Ultraman X The Movie",2016,"horror"),
                new Movie("Ultraman Orb The Movie",2017,"horror"),
                new Movie("Ultraman Geed The Movie",2018,"horror"),
                new Movie("Yongary: Monster from the Deep",1967,"horror"),
                new Movie("Space Amoeba",1970,"horror"),
                new Movie("Daigoro vs. Goliath",1972,"horror"),
                new Movie("Jumborg Ace & Giant",1974,"horror"),
                new Movie("King Kong (1976 film)|King Kong",1976,"horror"),
                new Movie("Spider-Man (1978 film)|Spider-Man",1978,"horror"),
                new Movie("Q - The Winged Serpent",1982,"horror"),
                new Movie("Pulgasari",1985,"horror"),
                new Movie("Yamato Takeru (film)|Yamato Takeru",1994,"horror"),
                new Movie("Gamera: Guardian of the Universe",1995,"horror"),
                new Movie("Gamera 2: Attack of Legion",1996,"horror"),
                new Movie("Gamera 3: The Revenge of Iris",1999,"horror"),
                new Movie("Rebirth of Mothra",1996,"horror"),
                new Movie("Rebirth of Mothra II",1997,"horror"),
                new Movie("Rebirth of Mothra III",1998,"horror"),
                new Movie("Zarkorr! The Invader",1996,"horror"),
                new Movie("Godzilla (1998 film)|Godzilla",1998,"horror"),
                new Movie("Yonggary (1999 film)|Yonggary",1999,"horror"),
                new Movie("Garuda (2004 film)|Garuda",2004,"horror"),
                new Movie("King Kong (2005 film)|King Kong",2005,"horror"),
                new Movie("Chousei Kantai Sazer-X the Movie: Fight! Star Warriors",2005,"horror"),
                new Movie("Negadon: The Monster from Mars",2005,"horror"),
                new Movie("Gamera the Brave",2006,"horror"),
                new Movie("D-War",2007,"horror"),
                new Movie("Deep Sea Monster Reigo",2008,"horror"),
                new Movie("Cloverfield",2008,"horror"),
                new Movie("10 Cloverfield Lane",2016,"horror"),
                new Movie("The Cloverfield Paradox",2018,"horror"),
                new Movie("Mega Shark Versus Giant Octopus",2009,"horror"),
                new Movie("Mega Shark Versus Crocosaurus",2010,"horror"),
                new Movie("Mega Shark Versus Mecha Shark",2014,"horror"),
                new Movie("Mega Shark vs. Kolossus",2015,"horror"),
                new Movie("Pacific Rim (film)|Pacific Rim",2013,"horror"),
                new Movie("Pacific Rim Uprising",2018,"horror"),
                new Movie("Godzilla (2014 film)|Godzilla",2014,"horror"),
                new Movie("Kong: Skull Island",2017,"horror"),
                new Movie("Godzilla: King of the Monsters (2019 film)|Godzilla: King of the Monsters",2019,"horror"),
                new Movie("Colossal (film)|Colossal",2017,"horror"),
                new Movie("Rampage (2018 film)|Rampage",2018,"horror"),
                new Movie("127 Hours",2010,"drama"),
                new Movie("Black Bread",2010,"drama"),
                new Movie("Black Swan",2010,"drama"),
                new Movie("Certified Copy",2010,"drama"),
                new Movie("The Disappearance of Haruhi Suzumiya",2010,"drama"),
                new Movie("The Fighter",2010,"drama"),
                new Movie("For Colored Girls",2010,"drama"),
                new Movie("Harry Potter and the Deathly Hallows – Part 1",2010,"drama"),
                new Movie("How To Train Your Dragon",2010,"drama"),
                new Movie("Kandahar",2010,"drama"),
                new Movie("The King's Speech",2010,"drama"),
                new Movie("My Name Is Khan",2010,"drama"),
                new Movie("The Social Network",2010,"drama"),
                new Movie("Winter's Bone",2010,"drama"),
                new Movie("Yuriko's Aroma[1]",2010,"drama"),
                new Movie("50/50",2011,"drama"),
                new Movie("Albert Nobbs",2011,"drama"),
                new Movie("Answers to Nothing",2011,"drama"),
                new Movie("The Artist",2011,"drama"),
                new Movie("The Descendants",2011,"drama"),
                new Movie("Extremely Loud & Incredibly Close",2011,"drama"),
                new Movie("The Girl with the Dragon Tattoo",2011,"drama"),
                new Movie("Harry Potter and the Deathly Hallows – Part 2",2011,"drama"),
                new Movie("The Help",2011,"drama"),
                new Movie("Hugo",2011,"drama"),
                new Movie("I Melt with You",2011,"drama"),
                new Movie("The Ides of March",2011,"drama"),
                new Movie("The Iron Lady",2011,"drama"),
                new Movie("Margin Call",2011,"drama"),
                new Movie("Melancholia",2011,"drama"),
                new Movie("Moneyball",2011,"drama"),
                new Movie("My Week with Marilyn",2011,"drama"),
                new Movie("One Day",2011,"drama"),
                new Movie("Real Steel",2011,"drama"),
                new Movie("Shame",2011,"drama"),
                new Movie("Take Shelter",2011,"drama"),
                new Movie("Toomelah",2011,"drama"),
                new Movie("The Tree of Life",2011,"drama"),
                new Movie("War Horse",2011,"drama"),
                new Movie("Warrior",2011,"drama"),
                new Movie("Toy Story",1995,"animated"),
                new Movie("A Bug's Life",1998,"animated"),
                new Movie("Toy Story 2",1999,"animated"),
                new Movie("Monsters, Inc.",2001,"animated"),
                new Movie("Finding Nemo",2003,"animated"),
                new Movie("The Incredibles",2004,"animated"),
                new Movie("Cars",2006,"animated"),
                new Movie("Ratatouille",2007,"animated"),
                new Movie("WALL-E",2008,"animated"),
                new Movie("Up",2009,"animated"),
                new Movie("Toy Story 3",2010,"animated"),
                new Movie("Cars 2",2011,"animated"),
                new Movie("Brave",2012,"animated"),
                new Movie("Monsters University",2013,"animated"),
                new Movie("Inside Out",2015,"animated"),
                new Movie("The Good Dinosaur",2015,"animated"),
                new Movie("Finding Dory",2016,"animated"),
                new Movie("Cars 3",2017,"animated"),
                new Movie("Coco",2017,"animated"),
                new Movie("Incredibles 2",2018,"animated")
            };
        public ArrayList getMovieList() => _movieList;

        public ArrayList getMovieList(string category)
        {
            ArrayList filteredList = new ArrayList();
            foreach (Movie movie in _movieList)
            {
                if(movie.GetCategory() == category)
                {
                    filteredList.Add(movie);
                }
            }
            filteredList.Sort();
            return filteredList;
        }
    }
}
